package store

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	GitCompatNone      = "none"
	GitCompatGenerated = "generated"
	GitCompatOverwrite = "overwrite"
)

type GitExportOptions struct {
	Gitignore  string
	Gitinclude string
}

type GitExportResult struct {
	Realm      string   `json:"realm"`
	Out        string   `json:"out"`
	GitCommit  string   `json:"git_commit,omitempty"`
	Generated  []string `json:"generated,omitempty"`
	Skipped    []string `json:"skipped,omitempty"`
	Gitignore  string   `json:"gitignore"`
	Gitinclude string   `json:"gitinclude"`
}

type compatFileResult struct {
	Generated bool
	Skipped   bool
}

func DefaultGitExportOptions() GitExportOptions {
	return GitExportOptions{Gitignore: GitCompatNone, Gitinclude: GitCompatNone}
}

func (o GitExportOptions) normalized() (GitExportOptions, error) {
	if o.Gitignore == "" {
		o.Gitignore = GitCompatNone
	}
	if o.Gitinclude == "" {
		o.Gitinclude = GitCompatNone
	}
	for name, value := range map[string]string{"gitignore": o.Gitignore, "gitinclude": o.Gitinclude} {
		switch value {
		case GitCompatNone, GitCompatGenerated, GitCompatOverwrite:
		default:
			return o, fmt.Errorf("unsupported %s mode %q", name, value)
		}
	}
	return o, nil
}

func (s *Store) GenerateGitCompatibilityFiles(out string, opts GitExportOptions) (*GitExportResult, error) {
	opts, err := opts.normalized()
	if err != nil {
		return nil, err
	}
	result := &GitExportResult{Out: out, Gitignore: opts.Gitignore, Gitinclude: opts.Gitinclude}
	manifest, err := LoadBootstrapManifest(s.Root)
	if err != nil {
		return nil, err
	}
	if file, err := generateCompatFile(filepath.Join(out, ".gitignore"), opts.Gitignore, generatedGitignore(manifest)); err != nil {
		return nil, err
	} else if file.Generated {
		result.Generated = append(result.Generated, ".gitignore")
	} else if file.Skipped {
		result.Skipped = append(result.Skipped, ".gitignore")
	}
	if file, err := generateCompatFile(filepath.Join(out, ".gitinclude"), opts.Gitinclude, generatedGitinclude(manifest)); err != nil {
		return nil, err
	} else if file.Generated {
		result.Generated = append(result.Generated, ".gitinclude")
	} else if file.Skipped {
		result.Skipped = append(result.Skipped, ".gitinclude")
	}
	return result, nil
}

func generateCompatFile(path, mode, content string) (compatFileResult, error) {
	switch mode {
	case GitCompatNone:
		return compatFileResult{}, nil
	case GitCompatGenerated:
		_, err := os.Stat(path)
		if err == nil {
			return compatFileResult{Skipped: true}, nil
		}
		if !os.IsNotExist(err) {
			return compatFileResult{}, err
		}
	case GitCompatOverwrite:
	default:
		return compatFileResult{}, fmt.Errorf("unsupported compatibility mode %q", mode)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return compatFileResult{}, err
	}
	return compatFileResult{Generated: true}, nil
}

func generatedGitignore(manifest *BootstrapManifest) string {
	patterns := append([]string{".glyph/**"}, manifest.GenesisImport.Exclude...)
	patterns = removeStrings(patterns, ".git/**")
	return generatedPatternFile("Glyph exclude rules for Git compatibility.", uniqueStrings(patterns))
}

func generatedGitinclude(manifest *BootstrapManifest) string {
	return generatedPatternFile("Glyph include rules for Git compatibility.", uniqueStrings(manifest.GenesisImport.Include))
}

func generatedPatternFile(note string, patterns []string) string {
	var b strings.Builder
	b.WriteString("# Generated by Glyph. Do not edit by hand unless you also update glyph.yaml.\n")
	b.WriteString("# " + note + "\n")
	b.WriteString("# Source: glyph.yaml genesis_import rules.\n\n")
	for _, pattern := range uniqueStrings(patterns) {
		b.WriteString(pattern)
		b.WriteByte('\n')
	}
	return b.String()
}

func uniqueStrings(in []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(in))
	for _, s := range in {
		s = strings.TrimSpace(s)
		if s == "" {
			continue
		}
		if seen[s] {
			continue
		}
		seen[s] = true
		out = append(out, s)
	}
	return out
}

func removeStrings(in []string, values ...string) []string {
	remove := map[string]bool{}
	for _, value := range values {
		remove[strings.TrimSpace(value)] = true
	}
	out := make([]string, 0, len(in))
	for _, s := range in {
		s = strings.TrimSpace(s)
		if remove[s] {
			continue
		}
		out = append(out, s)
	}
	return out
}
